.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 6/22/11               \" DATE 
.Dt toss 1      \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm toss
.\" The following lines are read in generating the apropos(man -k) database. Use only key
.\" words here as the database is built based on the words here and in the .ND line. 
.\" Use .Nm macro to designate other names for the documented program.
.Nd tosses files into the trash.
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl dfiIru              \" [-abcd]
.Ar file                 \" Underlined argument - use .Ar anywhere to underline
file ...                 \" Arguments
.Sh DESCRIPTION          \" Section Header - required - don't modify
The
.Nm
command moves specified files into the trash. It presents an interface similar
to the
.Xr rm 1
command, and is intended to (eventually) be a drop-in replacement for such.
.Pp
For each
.Ar file
specified on the command line,
.Nm
moves the
.Ar file
into the trash, possibly recursively.
.Pp                      \" Inserts a space
Options include:
.Bl -tag -width -indent  \" Begins a tagged list 
.It Fl d               \" Each item preceded by .It macro
Removes directories as well as files; if specified without --recursive,
then the directories specified are moved immediately to the trash; otherwise,
files are recursively all moved to the trash (to allow other options a
chance to have meaning).
.It Fl f, -force
Attempt to remove the files without prompting for confirmation, regardless
of the file's permissions.  If the file does not exist, do not display
a diagnostic message or modify the exit status to reflect an error.
.It Fl i, -interactive=always
Request confirmation before attempting to remove each file, regardless of
the file's permissions, or whether or not the standard input device is a
terminal.
.It Fl I, -interactive=once
Request confirmation once before attempting to remove more than three files,
or when removing recursively.
.It Fl -one-file-system
Do not remove files that exist on a different device than that of the argument,
when removing recursively.
.It Fl -preserve-root
Do not remove the `/' directory when removing recursively. This option is the
default behavior.
.It Fl -no-preserve-root
Does not treat `/' specially.
.It Fl r, R, -recursive
Toss directories and their contents into the trash.
.It Fl u, -unlink
Unlink files instead of moving them to the trash (that is, behave like
.Xr rm 1
).
.It Fl v, -verbose
Print a message about every file and directory moved to the trash.
.It Fl h, -help
Shows a help message and exits.
.It Fl -version
Shows a version message and exits.
.El                      \" Ends the list
.Pp
.Sh SEE ALSO 
.\" List links in ascending order by section, alphabetically within a section.
.\" Please do not reference files that do not exist without filing a bug report
.Xr rm 1
.\" .Sh BUGS              \" Document known, unremedied bugs 
.\" .Sh HISTORY           \" Document history if command behaves in a unique manner